version: "3"
services:
    www:
        container_name: php-docker-heml
        image: soft2dev/php-docker-heml:latest
        build: .
        ports:
            - "80:80"
        networks:
            - default


